#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Daito Tomita <s22C1090CW@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math

ans1 = 0
ans2 = 0
ans3 = 1
ans4 = 1.0

for line in sys.stdin:
    try:
        ans1 += int(line)
        ans2 -= int(line)
        ans3 *= int(line)
        ans4 /= int(line)
    except:
        ans1 += float(line)
        ans2 -= float(line)
        ans3 *= float(line)
        ans4 /= float(line)

print(ans1,":",ans2,":",ans3,":",round(ans4,5))
