#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Daito Tomita <s22C1090CW@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys

a = int(input())
b = str(input())

if b == 'km/s':
    x = a / 60
    y = a / 3600
    print(x,"km/m")
    print(y,"km/h")

elif b == 'km/m':
    x = a * 60
    y = a / 3600
    print(x,"km/s")
    print(y,"km/h")

elif b == 'km/h':
    x = a * 60
    y = a * 3600
    print(x,"km/m")
    print(y,"km/s")

else:
    print("error")
